trigger:
  branches:
    include:
    - '*'
  paths:
    exclude:
    - README.md

pr:
  branches:
    include:
    - '*'
  paths:
    exclude:
    - README.md

variables:
  buildConfiguration: 'Release'

jobs:
- job: Build
  displayName: 'Build job'
  pool:
    vmImage: 'windows-latest'

  steps:
    - script: |
        dotnet restore
        dotnet build --configuration $(buildConfiguration)
        dotnet test --configuration $(buildConfiguration)

    - task: DotNetCoreCLI@2
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
      inputs:
        command: publish
        arguments: '--configuration $(buildConfiguration) --output publish_output'
        projects: '*.csproj'
        publishWebProjects: false
        modifyOutputPath: false
        zipAfterPublish: false

    - task: ArchiveFiles@2
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
      displayName: "Archive files"
      inputs:
        rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output"
        includeRootFolder: false
        archiveFile: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"

    - task: PublishBuildArtifacts@1
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip'
        artifactName: 'drop'
